// Code generated by tygo. DO NOT EDIT.

//////////
// source: recipe.go

export interface Recipe {
  uuid: string;
  name: string;
  user_uuid: string;
  tag_string: string;
  created_at: string;
}
export interface File {
  uuid: string;
  recipe_uuid: string;
  url: string;
  page_number: number /* int */;
  image: boolean;
}
export interface Tag {
  uuid: string;
  name: string;
}
export interface RecipeTag {
  recipe_uuid: string;
  tag_uuid: string;
}
export interface RecipesResponse {
  recipeData: Recipe[];
  fileData: File[];
}
export interface UploadResponse {
  success: boolean;
  recipe: Recipe;
  tags: Tag[];
}
export interface RecipeStep {
  instruction: string;
  ingredients: string[];
}
export interface RecipeStepsResponse {
  steps: RecipeStep[];
}
